language: python
sudo: false
cache:
  directories:
    - eggs
    - downloads
python:
  - 2.7
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=4
    - python: "2.7"
      env: PLONE_VERSION=5.1
    - python: "2.7"
      env: PLONE_VERSION=5.2
    - python: "3.7"
      env: PLONE_VERSION=5.2
  sudo: true
  fast_finish: true
install:
  - sed -ie "s#plone-5#plone-$PLONE_VERSION#" buildout.cfg
  - sed -ie "s#plone-5#plone-$PLONE_VERSION#" travis.cfg
  - pip install -r requirements.txt
  - python bootstrap.py -c travis.cfg
  - bin/buildout -Nc travis.cfg buildout:download-cache=downloads buildout:eggs-directory=eggs annotate
  - bin/buildout -Nc travis.cfg buildout:download-cache=downloads buildout:eggs-directory=eggs
script:
  - bin/test
  - bin/coverage
after_success:
  - pip install coveralls==0.5
  - coveralls

notifications:
  email:
    - devs@imio.be
