language: python
python:
  - 2.7
install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap.py --version=2.5.3 -c travis.cfg
  - bin/buildout -Nc travis.cfg
script:
  - bin/test
  - bin/coverage
after_success:
  - pip install coveralls==0.5
  - coveralls

notifications:
  email:
    - devs@imio.be
