name: Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 2.7
            plone-version: 43
          - python-version: 2.7
            plone-version: 51
          - python-version: 3.7
            plone-version: 52
          - python-version: 3.8
            plone-version: 52
          - python-version: 3.8
            plone-version: "60"
    steps:
      # git checkout
      - uses: actions/checkout@v2
        
      # python setup
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # python eggs cache
      - name: Cache eggs
        uses: actions/cache@v2
        env:
          cache-name: cache-eggs
        with:
          path: ./eggs
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.python-version }}-${{ matrix.plone-version }}
          
      # build
      - name: build
        run: make plone${{ matrix.plone-version }}

      # test
      - name: test
        run: bin/test
