# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: 2.7
            plone: 4.3
          - python: 2.7
            plone: 5.1
          - python: 3.8
            plone: 5.2
          - python: 3.8
            plone: "6.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Setup Env
        run: |
          pip install -r requirements.txt
      - name: Cache eggs
        uses: actions/cache@v2
        env:
          cache-name: cache-eggs
        with:
          path: ~/buildout-cache/eggs
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ matrix.plone }}
          restore-keys: ${{ runner.os }}-test-${{ env.cache-name }}-${{ matrix.plone }}
      - name: buildout
        run: |
          sed -ie "s#plone-6.0#plone-${{matrix.plone}}#" buildout.cfg 
          buildout -c ci.cfg annotate
          buildout -c ci.cfg
      - name: test
        run: |
          bin/test -t !robot
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup Env
        run: |
          pip install -r requirements.txt
          pip install -U coveralls coverage
      - name: Cache eggs
        uses: actions/cache@v2
        env:
          cache-name: cache-eggs
        with:
          path: ~/buildout-cache/eggs
          key: ${{ runner.os }}-coverage-${{ env.cache-name }}
          restore-keys: ${{ runner.os }}-coverage-${{ env.cache-name }}
      - name: buildout
        run: |
          buildout -c ci.cfg
      - name: code-analysis
        run: |
          bin/code-analysis
      - name: test coverage
        run: |
          coverage run bin/test -t !robot
      - name: Publish to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github
